development: &default
  adapter: postgresql
  database: aact_back
  encoding: utf8
  min_messages: warning
  timeout: 5000

test:
  <<: *default
  database: aact_back_test

production: &deploy
  adapter: postgresql
  database: aact_back
  encoding: utf8
  min_messages: warning
  timeout: 5000

staging: *deploy

