development: &default
  adapter: postgresql
  database: aact_admin
  encoding: utf8
  min_messages: warning
  timeout: 5000

test:
  <<: *default
  database: aact_admin_test

production: &deploy
  encoding: utf8
  min_messages: warning
  timeout: 5000

staging: *deploy

