development: &default
  adapter: postgresql
  database: back_aact
  encoding: utf8
  min_messages: warning
  timeout: 5000

test:
  <<: *default
  database: back_aact_test

production: &deploy
  adapter: postgresql
  database: back_aact
  encoding: utf8
  min_messages: warning
  timeout: 5000

staging: *deploy

