- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - set_fact:
        buckets:
          - aact-dev
          - aact-prod

    - name: create S3 buckets
      s3_bucket:
        name: "{{ item }}"
        policy:
          Version: "2012-10-17"
          Statement:
            -
              Sid: "Stmt1470845581678"
              Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetBucketLocation"
                - "s3:ListBucket"
              Resource: "arn:aws:s3:::{{ item }}"
            -
              Sid: "Stmt1470845605315"
              Effect: "Allow"
              Principal: "*"
              Action: "s3:GetObject"
              Resource: "arn:aws:s3:::{{ item }}/*"
      with_items: "{{ buckets }}"

    - name: create agent IAM accounts
      iam:
        iam_type: user
        name: "{{ item }}-agent"
        state: present
      with_items: "{{ buckets }}"

    - name: create dev-agent-policy
      iam_policy:
        state: present
        iam_name: aact-dev-agent
        iam_type: user
        policy_name: aact-dev-agent-policy
        policy_document: aact-dev-agent-policy.json

    - name: create prod-agent-policy
      iam_policy:
        state: present
        iam_name: aact-prod-agent
        iam_type: user
        policy_name: aact-prod-agent-policy
        policy_document: aact-prod-agent-policy.json

# prod RDS security group
#
# prod RDS postgres instance
#  - dbt2.medium, 20 GB
#
# create RO User in RDS postgres (sql script)
